---
- hosts: all
  tasks:
    - name: Install prerequisites
      become: true
      apt:
        name:
          [
            "apt-transport-https",
            "ca-certificates",
            "curl",
            "software-properties-common",
            "zip",
          ]
        update_cache: yes

    ######## install docker
    - name: Add Docker GPG key
      when: install_docker
      become: true
      apt_key: url=https://download.docker.com/linux/ubuntu/gpg

    - name: Add Docker APT repository
      become: true
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

    - name: Install Docker
      when: install_docker
      become: true
      apt:
        name: docker-ce
        update_cache: yes

    # sudo groupadd docker
    - name: Add remote "ubuntu" user to "docker" group
      when: install_docker
      become: true
      user:
        name: ubuntu
        group: docker
        append: yes

    ######## install php
    - name: Add php APT repository
      when: install_php
      become: true
      apt_repository:
        repo: ppa:ondrej/php
    - name: Add php{{ php_version }}
      when: install_php
      become: true
      apt:
        name:
          [
            "php{{ php_version }}-fpm",
            "php{{ php_version }}-curl",
            "php{{ php_version }}-mbstring",
            "php{{ php_version }}-xml",
            "php{{ php_version }}-zip",
            "php{{ php_version }}-gd",
            "php{{ php_version }}-soap",
            "php{{ php_version }}-pdo",
            "php{{ php_version }}-mysql",
            "php{{ php_version }}-sqlite3",
            "php{{ php_version }}-dev",
            "php{{ php_version }}-intl",
          ]
        update_cache: yes

    ######## zsh
    - name: Add zsh
      become: true
      apt:
        name: ["zsh"]
        update_cache: yes

    - name: Cloning oh-my-zsh
      git: repo=https://github.com/robbyrussell/oh-my-zsh
        dest=~/.oh-my-zsh
      register: cloning

    # - name: Creating new ~/.zshrc
    #   copy: src=~/.oh-my-zsh/templates/zshrc.zsh-template
    #     dest=~/.zshrc
    #   when: cloning|done

    ######## nvm
    - name: nvm
      when: install_nvm
      become: true
      shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/{{ nvm_version }}/install.sh | bash
      args:
        creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"

    ######## golang
    - name: install golang
      when: install_go
      become: true
      unarchive:
        src: "https://dl.google.com/go/go{{ go_version }}.linux-amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: yes
    - name: update zshrc
      when: install_go
      shell: >
        echo "export PATH=$PATH:/usr/local/bin/go/bin" >> ~/.profile

    ######## nginx
    - name: install nginx
      when: install_nginx
      become: true
      apt:
        name: ["nginx"]
        update_cache: yes
